### ISSUE TITLE
Refatoração das US: 01, 02, 03 e 18

### ISSUE THREAD

**Issue by fellipe-araujo** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#10]
## Descrição

Refatorar front-end e back-end de acordo com o que foi discutido presencialmente na reunião do dia 15/07/2022.

## Issues relacionadas para a refatoração

* #1
* #2 
* #3 
* #8

**Comment by ErickGiffoni** [comment]
Obg por já criarem a issue e começarem!
@fellipe-araujo e @mateusbrandaot quanto tempo vcs estimam para a refatoração ?

**Comment by ErickGiffoni** [comment]
@fellipe-araujo talvez vc já possa fazer a #12 nessa mesma issue aqui, o que acha ?

**Comment by fellipe-araujo** [comment]
Como o front-end terá muitas mudanças e pouco aproveitamento de código pelo que eu pude analisar, acredito que leve 5 horas somente para o front-end. Já para o back-end, acredito que seja mais rápido, acredito que leve umas 3 horas (pelo motivo de ter que criar uma nova tabela por conta de um relacionamento NxM), totalizando um total de 8 horas.

Como já estou refatorando o front-end, posso fazer a issue #12 juntamente.
