### ISSUE TITLE
RF 7 - Visualizar a temperatura atual do flash cure

### ISSUE THREAD

**Issue by ErickGiffoni** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#11]
# Eu, como usuário/sistema, desejo

- Tipo: Funcional
- Prioridade: 
- Sprint: 
- Estimativa de esforço (em horas):

## Tasks

- [ ] foo-bar
- [ ] bar-foo

## Critérios de aceitação

- [ ] foo-bar
- [ ] bar-foo

**Comment by Projeto-Carrossel-Serigrafia-PI2** [comment]
Será feita na issue #32
