### ISSUE TITLE
Implementar getTemperatues com o sensor

### ISSUE THREAD

**Issue by Projeto-Carrossel-Serigrafia-PI2** [Projeto-Carrossel-Serigrafia-PI2/Projeto-Carrossel-Semi-Automatico-PI2-Documentacao#32]

**Comment by ErickGiffoni** [comment]
@SamButers acredito que já fez essa issue na branch dos periféricos, certo ?

**Comment by SamButers** [comment]
> @SamButers acredito que já fez essa issue na branch dos periféricos, certo ?

Sim, já está pronto lá.
Entrará com o PR.
